package com.qiguliuxing.dts.db.dao;

import com.qiguliuxing.dts.db.domain.DtsAccountTrace;
import com.qiguliuxing.dts.db.domain.DtsAccountTraceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DtsAccountTraceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_account_trace
     *
     * @mbg.generated
     */
    long countByExample(DtsAccountTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_account_trace
     *
     * @mbg.generated
     */
    int deleteByExample(DtsAccountTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_account_trace
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_account_trace
     *
     * @mbg.generated
     */
    int insert(DtsAccountTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_account_trace
     *
     * @mbg.generated
     */
    int insertSelective(DtsAccountTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_account_trace
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsAccountTrace selectOneByExample(DtsAccountTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_account_trace
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsAccountTrace selectOneByExampleSelective(@Param("example") DtsAccountTraceExample example, @Param("selective") DtsAccountTrace.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_account_trace
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<DtsAccountTrace> selectByExampleSelective(@Param("example") DtsAccountTraceExample example, @Param("selective") DtsAccountTrace.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_account_trace
     *
     * @mbg.generated
     */
    List<DtsAccountTrace> selectByExample(DtsAccountTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_account_trace
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsAccountTrace selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DtsAccountTrace.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_account_trace
     *
     * @mbg.generated
     */
    DtsAccountTrace selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_account_trace
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DtsAccountTrace record, @Param("example") DtsAccountTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_account_trace
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DtsAccountTrace record, @Param("example") DtsAccountTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_account_trace
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DtsAccountTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_account_trace
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DtsAccountTrace record);
}