package com.qiguliuxing.dts.db.dao;

import com.qiguliuxing.dts.db.domain.DtsAd;
import com.qiguliuxing.dts.db.domain.DtsAdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DtsAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_ad
     *
     * @mbg.generated
     */
    long countByExample(DtsAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_ad
     *
     * @mbg.generated
     */
    int deleteByExample(DtsAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_ad
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_ad
     *
     * @mbg.generated
     */
    int insert(DtsAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_ad
     *
     * @mbg.generated
     */
    int insertSelective(DtsAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsAd selectOneByExample(DtsAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsAd selectOneByExampleSelective(@Param("example") DtsAdExample example, @Param("selective") DtsAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<DtsAd> selectByExampleSelective(@Param("example") DtsAdExample example, @Param("selective") DtsAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_ad
     *
     * @mbg.generated
     */
    List<DtsAd> selectByExample(DtsAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsAd selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DtsAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_ad
     *
     * @mbg.generated
     */
    DtsAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsAd selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_ad
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DtsAd record, @Param("example") DtsAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_ad
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DtsAd record, @Param("example") DtsAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DtsAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DtsAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") DtsAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}