package com.qiguliuxing.dts.db.dao;

import com.qiguliuxing.dts.db.domain.DtsDelPicture;
import com.qiguliuxing.dts.db.domain.DtsDelPictureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DtsDelPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_del_picture
     *
     * @mbg.generated
     */
    long countByExample(DtsDelPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_del_picture
     *
     * @mbg.generated
     */
    int deleteByExample(DtsDelPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_del_picture
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_del_picture
     *
     * @mbg.generated
     */
    int insert(DtsDelPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_del_picture
     *
     * @mbg.generated
     */
    int insertSelective(DtsDelPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_del_picture
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsDelPicture selectOneByExample(DtsDelPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_del_picture
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsDelPicture selectOneByExampleSelective(@Param("example") DtsDelPictureExample example, @Param("selective") DtsDelPicture.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_del_picture
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<DtsDelPicture> selectByExampleSelective(@Param("example") DtsDelPictureExample example, @Param("selective") DtsDelPicture.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_del_picture
     *
     * @mbg.generated
     */
    List<DtsDelPicture> selectByExample(DtsDelPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_del_picture
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsDelPicture selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DtsDelPicture.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_del_picture
     *
     * @mbg.generated
     */
    DtsDelPicture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_del_picture
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DtsDelPicture record, @Param("example") DtsDelPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_del_picture
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DtsDelPicture record, @Param("example") DtsDelPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_del_picture
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DtsDelPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_del_picture
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DtsDelPicture record);
}