package com.qiguliuxing.dts.db.dao;

import com.qiguliuxing.dts.db.domain.DtsFootprint;
import com.qiguliuxing.dts.db.domain.DtsFootprintExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DtsFootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    long countByExample(DtsFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    int deleteByExample(DtsFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    int insert(DtsFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    int insertSelective(DtsFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsFootprint selectOneByExample(DtsFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsFootprint selectOneByExampleSelective(@Param("example") DtsFootprintExample example, @Param("selective") DtsFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<DtsFootprint> selectByExampleSelective(@Param("example") DtsFootprintExample example, @Param("selective") DtsFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    List<DtsFootprint> selectByExample(DtsFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsFootprint selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DtsFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    DtsFootprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsFootprint selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DtsFootprint record, @Param("example") DtsFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DtsFootprint record, @Param("example") DtsFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DtsFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DtsFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") DtsFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}