package com.qiguliuxing.dts.db.dao;

import com.qiguliuxing.dts.db.domain.DtsGoodsProduct;
import com.qiguliuxing.dts.db.domain.DtsGoodsProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DtsGoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_product
     *
     * @mbg.generated
     */
    long countByExample(DtsGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_product
     *
     * @mbg.generated
     */
    int deleteByExample(DtsGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_product
     *
     * @mbg.generated
     */
    int insert(DtsGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_product
     *
     * @mbg.generated
     */
    int insertSelective(DtsGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsGoodsProduct selectOneByExample(DtsGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsGoodsProduct selectOneByExampleSelective(@Param("example") DtsGoodsProductExample example, @Param("selective") DtsGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<DtsGoodsProduct> selectByExampleSelective(@Param("example") DtsGoodsProductExample example, @Param("selective") DtsGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_product
     *
     * @mbg.generated
     */
    List<DtsGoodsProduct> selectByExample(DtsGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsGoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DtsGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_product
     *
     * @mbg.generated
     */
    DtsGoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsGoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DtsGoodsProduct record, @Param("example") DtsGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DtsGoodsProduct record, @Param("example") DtsGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DtsGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DtsGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") DtsGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_goods_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}