package com.qiguliuxing.dts.db.dao;

import com.qiguliuxing.dts.db.domain.DtsUserFormid;
import com.qiguliuxing.dts.db.domain.DtsUserFormidExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DtsUserFormidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user_formid
     *
     * @mbg.generated
     */
    long countByExample(DtsUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user_formid
     *
     * @mbg.generated
     */
    int deleteByExample(DtsUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user_formid
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user_formid
     *
     * @mbg.generated
     */
    int insert(DtsUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user_formid
     *
     * @mbg.generated
     */
    int insertSelective(DtsUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsUserFormid selectOneByExample(DtsUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsUserFormid selectOneByExampleSelective(@Param("example") DtsUserFormidExample example, @Param("selective") DtsUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<DtsUserFormid> selectByExampleSelective(@Param("example") DtsUserFormidExample example, @Param("selective") DtsUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user_formid
     *
     * @mbg.generated
     */
    List<DtsUserFormid> selectByExample(DtsUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsUserFormid selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DtsUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user_formid
     *
     * @mbg.generated
     */
    DtsUserFormid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsUserFormid selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user_formid
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DtsUserFormid record, @Param("example") DtsUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user_formid
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DtsUserFormid record, @Param("example") DtsUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user_formid
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DtsUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user_formid
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DtsUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") DtsUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}